"""frente1_wa_phone_tenant_binding

Revision ID: 117dba1c46eb
Revises: 73a2a208e666
Create Date: 2026-04-29 18:13:07.311449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117dba1c46eb'
down_revision: Union[str, Sequence[str], None] = '73a2a208e666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_phone_tenant_bindings',
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('display_phone_number', sa.String(length=40), nullable=True),
    sa.Column('verify_token', sa.String(length=120), nullable=True),
    sa.Column('app_secret', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('phone_number_id')
    )
    with op.batch_alter_table('wa_phone_tenant_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wa_phone_tenant_bindings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_phone_tenant_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wa_phone_tenant_bindings_tenant_id'))

    op.drop_table('wa_phone_tenant_bindings')
    # ### end Alembic commands ###
