"""frente4_13_daily_horoscope

Revision ID: 16ef806c29dd
Revises: b486d6eb58a5
Create Date: 2026-04-29 15:12:38.835233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ef806c29dd'
down_revision: Union[str, Sequence[str], None] = 'b486d6eb58a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_horoscopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signo', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('generated_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'signo', 'lang', name='uq_daily_horoscope_date_sign_lang')
    )
    with op.batch_alter_table('daily_horoscopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_horoscopes_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_horoscopes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_horoscopes_signo'), ['signo'], unique=False)

    op.create_table('horoscope_automations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('send_hour_local', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('segment_filter', sa.String(length=20), nullable=False),
    sa.Column('custom_prefix', sa.Text(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horoscope_automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horoscope_automations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horoscope_automations_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('horoscope_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lead_id', 'date', name='uq_horoscope_delivery_tenant_lead_date')
    )
    with op.batch_alter_table('horoscope_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horoscope_deliveries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_horoscope_deliveries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horoscope_deliveries_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horoscope_deliveries_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('signo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('consents', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.create_index(batch_op.f('ix_leads_signo'), ['signo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_signo'))
        batch_op.drop_column('consents')
        batch_op.drop_column('timezone')
        batch_op.drop_column('signo')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('horoscope_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horoscope_deliveries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_horoscope_deliveries_lead_id'))
        batch_op.drop_index(batch_op.f('ix_horoscope_deliveries_id'))
        batch_op.drop_index(batch_op.f('ix_horoscope_deliveries_date'))

    op.drop_table('horoscope_deliveries')
    with op.batch_alter_table('horoscope_automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horoscope_automations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_horoscope_automations_id'))

    op.drop_table('horoscope_automations')
    with op.batch_alter_table('daily_horoscopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_horoscopes_signo'))
        batch_op.drop_index(batch_op.f('ix_daily_horoscopes_id'))
        batch_op.drop_index(batch_op.f('ix_daily_horoscopes_date'))

    op.drop_table('daily_horoscopes')
    # ### end Alembic commands ###
