"""frente3_12_quick_replies

Revision ID: 198df643d448
Revises: f8b260830503
Create Date: 2026-04-29 15:36:35.694233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198df643d448'
down_revision: Union[str, Sequence[str], None] = 'f8b260830503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('shortcut_number', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'shortcut_number', name='uq_quick_reply_tenant_shortcut')
    )
    with op.batch_alter_table('quick_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_replies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quick_replies_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_replies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quick_replies_id'))

    op.drop_table('quick_replies')
    # ### end Alembic commands ###
