"""voice_clone_is_default

Revision ID: 215b346addc7
Revises: fdf25ed08916
Create Date: 2026-04-29 20:33:10.541295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215b346addc7'
down_revision: Union[str, Sequence[str], None] = 'fdf25ed08916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_clones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_voice_clones_is_default'), ['is_default'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_clones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_clones_is_default'))
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
