"""frente4_14_voice_clones_audio_gen

Revision ID: 2236339dc7e0
Revises: 5dfeb05a3764
Create Date: 2026-04-29 14:40:35.698673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2236339dc7e0'
down_revision: Union[str, Sequence[str], None] = '5dfeb05a3764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_clones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_voice_id', sa.String(length=120), nullable=False),
    sa.Column('enrollment_audio_url', sa.Text(), nullable=True),
    sa.Column('sample_audio_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_clones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_clones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_clones_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audio_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('voice_clone_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chars_count', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_clone_id'], ['voice_clones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_generations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_generations_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_generations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audio_generations_id'))

    op.drop_table('audio_generations')
    with op.batch_alter_table('voice_clones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_clones_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_voice_clones_id'))

    op.drop_table('voice_clones')
    # ### end Alembic commands ###
