"""frente5_4_onboarding_templates_tarot

Revision ID: 2cc3573e73e8
Revises: 894412876bdb
Create Date: 2026-04-29 14:19:31.479413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc3573e73e8'
down_revision: Union[str, Sequence[str], None] = '894412876bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('preview_image_url', sa.String(length=500), nullable=True),
    sa.Column('ticket_brl_avg', sa.Integer(), nullable=False),
    sa.Column('blueprint_json', sa.JSON(), nullable=False),
    sa.Column('agent_json', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('seller_tenant_id', sa.String(length=64), nullable=True),
    sa.Column('price_brl_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarot_decks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_milestones',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('milestone_key', sa.String(length=40), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'milestone_key')
    )
    op.create_table('tarot_cards',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('deck_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('arcana', sa.String(length=10), nullable=False),
    sa.Column('suit', sa.String(length=20), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('meaning_upright', sa.Text(), nullable=True),
    sa.Column('meaning_reversed', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['tarot_decks.id'], ),
    sa.PrimaryKeyConstraint('id', 'deck_id')
    )
    op.create_table('tarot_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('attended_by_user_id', sa.Integer(), nullable=True),
    sa.Column('spread_type', sa.String(length=40), nullable=False),
    sa.Column('deck_id', sa.String(length=40), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('sent_to_lead', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attended_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarot_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarot_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarot_readings_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarot_readings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarot_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarot_readings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tarot_readings_lead_id'))
        batch_op.drop_index(batch_op.f('ix_tarot_readings_id'))

    op.drop_table('tarot_readings')
    op.drop_table('tarot_cards')
    op.drop_table('onboarding_milestones')
    op.drop_table('tarot_decks')
    op.drop_table('flow_templates')
    # ### end Alembic commands ###
