"""frente4_1_lunar_phases

Revision ID: 3ad6d75bb41a
Revises: 5e713846895f
Create Date: 2026-04-29 14:54:08.266203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad6d75bb41a'
down_revision: Union[str, Sequence[str], None] = '5e713846895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunar_phases',
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phase_name', sa.String(length=20), nullable=False),
    sa.Column('illumination_pct', sa.Float(), nullable=False),
    sa.Column('zodiac_sign', sa.String(length=20), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('special_label', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lunar_phases')
    # ### end Alembic commands ###
