"""audio_library_4_17

Revision ID: 4290f03bd336
Revises: 215b346addc7
Create Date: 2026-04-29 20:39:28.508235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4290f03bd336'
down_revision: Union[str, Sequence[str], None] = '215b346addc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_library_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_library_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_library_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('voice_clones', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_clones', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('audio_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_library_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audio_library_id'))
        batch_op.drop_index(batch_op.f('ix_audio_library_category'))

    op.drop_table('audio_library')
    # ### end Alembic commands ###
