"""frente3_18_23_lead_extended_notes

Revision ID: 4611cf7afb89
Revises: 198df643d448
Create Date: 2026-04-29 15:41:25.491400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4611cf7afb89'
down_revision: Union[str, Sequence[str], None] = '198df643d448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_notes_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_notes_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('cidade')
        batch_op.drop_column('idade')

    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lead_notes_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_notes_id'))

    op.drop_table('lead_notes')
    # ### end Alembic commands ###
