"""wa_binding_subscribe_inbound_telemetry

Revision ID: 4c59c59a9a00
Revises: 117dba1c46eb
Create Date: 2026-04-29 19:57:53.294096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c59c59a9a00'
down_revision: Union[str, Sequence[str], None] = '117dba1c46eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_phone_tenant_bindings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subscribe_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('first_inbound_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('inbound_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_phone_tenant_bindings', schema=None) as batch_op:
        batch_op.drop_column('inbound_count')
        batch_op.drop_column('last_inbound_at')
        batch_op.drop_column('first_inbound_at')
        batch_op.drop_column('subscribe_error')
        batch_op.drop_column('subscribed_at')

    # ### end Alembic commands ###
