"""daily_personal_messages_4_27

Revision ID: 56a3674793bd
Revises: 4290f03bd336
Create Date: 2026-04-29 20:45:31.812880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a3674793bd'
down_revision: Union[str, Sequence[str], None] = '4290f03bd336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_personal_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chars_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lead_id', 'date', name='uq_dpm_tenant_lead_date')
    )
    with op.batch_alter_table('daily_personal_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_personal_messages_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_personal_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_personal_messages_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_personal_messages_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_personal_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_personal_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_daily_personal_messages_lead_id'))
        batch_op.drop_index(batch_op.f('ix_daily_personal_messages_id'))
        batch_op.drop_index(batch_op.f('ix_daily_personal_messages_date'))

    op.drop_table('daily_personal_messages')
    # ### end Alembic commands ###
