"""frente4_19_spiritual_intent

Revision ID: 5b07d79c7608
Revises: 4611cf7afb89
Create Date: 2026-04-29 15:45:36.797583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b07d79c7608'
down_revision: Union[str, Sequence[str], None] = '4611cf7afb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spiritual_category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('spiritual_intent', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('spiritual_intent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_spiritual_category'), ['spiritual_category'], unique=False)

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spiritual_intent', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_column('spiritual_intent')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_spiritual_category'))
        batch_op.drop_column('spiritual_intent_at')
        batch_op.drop_column('spiritual_intent')
        batch_op.drop_column('spiritual_category')

    # ### end Alembic commands ###
