"""frente7_1 pix_payments

Revision ID: 5dfeb05a3764
Revises: 2cc3573e73e8
Create Date: 2026-04-29 14:34:32.733897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfeb05a3764'
down_revision: Union[str, Sequence[str], None] = '2cc3573e73e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pix_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('flow_run_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=False),
    sa.Column('amount_brl_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qr_code_image_url', sa.Text(), nullable=True),
    sa.Column('qr_code_text', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pix_payments_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pix_payments_provider_payment_id'), ['provider_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pix_payments_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pix_payments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_pix_payments_provider_payment_id'))
        batch_op.drop_index(batch_op.f('ix_pix_payments_lead_id'))
        batch_op.drop_index(batch_op.f('ix_pix_payments_id'))

    op.drop_table('pix_payments')
    # ### end Alembic commands ###
