"""frente7_15_affiliate_program

Revision ID: 5e713846895f
Revises: 2236339dc7e0
Create Date: 2026-04-29 14:49:27.499553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e713846895f'
down_revision: Union[str, Sequence[str], None] = '2236339dc7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ref_code', sa.String(length=40), nullable=False),
    sa.Column('pix_key', sa.String(length=120), nullable=True),
    sa.Column('pix_key_type', sa.String(length=20), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('active_referrals', sa.Integer(), nullable=False),
    sa.Column('total_earned_brl_cents', sa.Integer(), nullable=False),
    sa.Column('total_paid_out_brl_cents', sa.Integer(), nullable=False),
    sa.Column('commission_pct', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliates_ref_code'), ['ref_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_affiliates_user_id'), ['user_id'], unique=True)

    op.create_table('affiliate_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('amount_brl_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pix_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_payouts_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_payouts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_payouts_period_yyyymm'), ['period_yyyymm'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=True),
    sa.Column('referred_email', sa.String(length=200), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_commission_earned_cents', sa.Integer(), nullable=False),
    sa.Column('last_recurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cookie_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_affiliate_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('affiliate_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_payouts_period_yyyymm'))
        batch_op.drop_index(batch_op.f('ix_affiliate_payouts_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_payouts_affiliate_id'))

    op.drop_table('affiliate_payouts')
    with op.batch_alter_table('affiliates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliates_user_id'))
        batch_op.drop_index(batch_op.f('ix_affiliates_ref_code'))
        batch_op.drop_index(batch_op.f('ix_affiliates_id'))

    op.drop_table('affiliates')
    # ### end Alembic commands ###
