"""baseline_schema

Revision ID: 5ee5408501f7
Revises: 
Create Date: 2026-04-29 11:31:54.979344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee5408501f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('url_publica', sa.Text(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_audio_cache_id'), ['id'], unique=False)

    op.create_table('flow_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_json', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_flow_blueprint_tenant_slug')
    )
    with op.batch_alter_table('flow_blueprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_blueprints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprints_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprints_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('node_atual', sa.String(length=100), nullable=True),
    sa.Column('node_historico', sa.JSON(), nullable=True),
    sa.Column('estado_coleta', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('arquetipo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tempo_sofrimento', sa.String(length=100), nullable=True),
    sa.Column('resumo_dor', sa.Text(), nullable=True),
    sa.Column('desejo_oculto', sa.Text(), nullable=True),
    sa.Column('nome_mecanismo', sa.String(length=200), nullable=True),
    sa.Column('objecao_silenciosa', sa.Text(), nullable=True),
    sa.Column('nivel_energia', sa.String(length=50), nullable=True),
    sa.Column('tom_sugerido', sa.String(length=50), nullable=True),
    sa.Column('score_engajamento', sa.Float(), nullable=True),
    sa.Column('ultima_intencao', sa.String(length=50), nullable=True),
    sa.Column('ultimo_sentimento', sa.String(length=50), nullable=True),
    sa.Column('recovery_stage', sa.Integer(), nullable=True),
    sa.Column('recovery_bloqueado', sa.Boolean(), nullable=True),
    sa.Column('ultimo_recovery_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_out', sa.Boolean(), nullable=True),
    sa.Column('convertido', sa.Boolean(), nullable=True),
    sa.Column('produto_comprado', sa.String(length=200), nullable=True),
    sa.Column('bot_pausado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'telefone', name='uq_lead_tenant_phone')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_bot_pausado'), ['bot_pausado'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_convertido'), ['convertido'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_node_atual'), ['node_atual'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_recovery_bloqueado'), ['recovery_bloqueado'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_telefone'), ['telefone'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('studio_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=32), nullable=False),
    sa.Column('draft_json', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_agents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('templates_msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_base', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('node_origem', sa.String(length=100), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('score_conversao', sa.Float(), nullable=True),
    sa.Column('total_usos', sa.Integer(), nullable=True),
    sa.Column('total_conversoes', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates_msg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_msg_chave_base'), ['chave_base'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_msg_id'), ['id'], unique=False)

    op.create_table('tenant_flow_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_cipher', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_tenant_flow_secret_key')
    )
    with op.batch_alter_table('tenant_flow_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_flow_secrets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_flow_secrets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_flow_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_tenant_flow_var_key')
    )
    with op.batch_alter_table('tenant_flow_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_flow_variables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_flow_variables_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('eventos_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('dados', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_audit_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_audit_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_audit_timestamp'), ['timestamp'], unique=False)

    op.create_table('flow_blueprint_acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('principal', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['flow_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'principal', name='uq_flow_bp_acl_principal')
    )
    with op.batch_alter_table('flow_blueprint_acl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_blueprint_acl_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_acl_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_acl_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flow_blueprint_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('node_ref', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_label', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['flow_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_blueprint_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_blueprint_comments_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_comments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flow_blueprint_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('lock_holder', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['flow_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_blueprint_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_blueprint_locks_blueprint_id'), ['blueprint_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_locks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_locks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flow_blueprint_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('body_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['flow_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'version_number', name='uq_flow_bp_version_num')
    )
    with op.batch_alter_table('flow_blueprint_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_blueprint_versions_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_blueprint_versions_id'), ['id'], unique=False)

    op.create_table('flow_publish',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('published_blueprint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['published_blueprint_id'], ['flow_blueprints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_publish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_publish_published_blueprint_id'), ['published_blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_publish_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('flow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['flow_blueprints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_runs_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_runs_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('flow_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('cron_expr', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['flow_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_schedules_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_schedules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lead_behavior_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('node_atual', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_behavior_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_behavior_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_behavior_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_behavior_events_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_behavior_events_node_atual'), ['node_atual'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_behavior_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_behavior_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.String(length=10), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('intencao', sa.String(length=50), nullable=True),
    sa.Column('sentimento', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensagens_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensagens_timestamp'), ['timestamp'], unique=False)

    op.create_table('payment_event_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'event_id', name='uq_payment_event_receipt')
    )
    with op.batch_alter_table('payment_event_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_event_receipts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_event_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_event_receipts_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_event_receipts_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_event_receipts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_event_receipts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('studio_agent_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('body_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['studio_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_agent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_agent_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_agent_versions_id'), ['id'], unique=False)

    op.create_table('whatsapp_inbound_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('wamid', sa.String(length=128), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'wamid', name='uq_wa_receipt_tenant_wamid')
    )
    with op.batch_alter_table('whatsapp_inbound_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_inbound_receipts_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_inbound_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_inbound_receipts_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_inbound_receipts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_inbound_receipts_wamid'), ['wamid'], unique=False)

    op.create_table('flow_run_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['flow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_flow_run_event_seq')
    )
    with op.batch_alter_table('flow_run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_run_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('studio_publish',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('published_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['published_version_id'], ['studio_agent_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_publish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_publish_published_version_id'), ['published_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_publish_tenant_id'), ['tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_publish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_publish_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_studio_publish_published_version_id'))

    op.drop_table('studio_publish')
    with op.batch_alter_table('flow_run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_run_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_flow_run_events_id'))

    op.drop_table('flow_run_events')
    with op.batch_alter_table('whatsapp_inbound_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_inbound_receipts_wamid'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_inbound_receipts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_inbound_receipts_lead_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_inbound_receipts_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_inbound_receipts_criado_em'))

    op.drop_table('whatsapp_inbound_receipts')
    with op.batch_alter_table('studio_agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_agent_versions_id'))
        batch_op.drop_index(batch_op.f('ix_studio_agent_versions_agent_id'))

    op.drop_table('studio_agent_versions')
    with op.batch_alter_table('payment_event_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_event_receipts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_event_receipts_provider'))
        batch_op.drop_index(batch_op.f('ix_payment_event_receipts_processed_at'))
        batch_op.drop_index(batch_op.f('ix_payment_event_receipts_lead_id'))
        batch_op.drop_index(batch_op.f('ix_payment_event_receipts_id'))
        batch_op.drop_index(batch_op.f('ix_payment_event_receipts_event_id'))

    op.drop_table('payment_event_receipts')
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagens_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mensagens_lead_id'))
        batch_op.drop_index(batch_op.f('ix_mensagens_id'))

    op.drop_table('mensagens')
    with op.batch_alter_table('lead_behavior_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_behavior_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_lead_behavior_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lead_behavior_events_node_atual'))
        batch_op.drop_index(batch_op.f('ix_lead_behavior_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_behavior_events_id'))
        batch_op.drop_index(batch_op.f('ix_lead_behavior_events_event_type'))

    op.drop_table('lead_behavior_events')
    with op.batch_alter_table('flow_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_schedules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_schedules_id'))
        batch_op.drop_index(batch_op.f('ix_flow_schedules_blueprint_id'))

    op.drop_table('flow_schedules')
    with op.batch_alter_table('flow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_runs_lead_id'))
        batch_op.drop_index(batch_op.f('ix_flow_runs_id'))
        batch_op.drop_index(batch_op.f('ix_flow_runs_blueprint_id'))

    op.drop_table('flow_runs')
    with op.batch_alter_table('flow_publish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_publish_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_publish_published_blueprint_id'))

    op.drop_table('flow_publish')
    with op.batch_alter_table('flow_blueprint_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_versions_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_versions_blueprint_id'))

    op.drop_table('flow_blueprint_versions')
    with op.batch_alter_table('flow_blueprint_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_locks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_locks_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_locks_blueprint_id'))

    op.drop_table('flow_blueprint_locks')
    with op.batch_alter_table('flow_blueprint_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_comments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_comments_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_comments_blueprint_id'))

    op.drop_table('flow_blueprint_comments')
    with op.batch_alter_table('flow_blueprint_acl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_acl_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_acl_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprint_acl_blueprint_id'))

    op.drop_table('flow_blueprint_acl')
    with op.batch_alter_table('eventos_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_audit_timestamp'))
        batch_op.drop_index(batch_op.f('ix_eventos_audit_lead_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_audit_id'))

    op.drop_table('eventos_audit')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenant_flow_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_flow_variables_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_flow_variables_id'))

    op.drop_table('tenant_flow_variables')
    with op.batch_alter_table('tenant_flow_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_flow_secrets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_flow_secrets_id'))

    op.drop_table('tenant_flow_secrets')
    with op.batch_alter_table('templates_msg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_msg_id'))
        batch_op.drop_index(batch_op.f('ix_templates_msg_chave_base'))

    op.drop_table('templates_msg')
    with op.batch_alter_table('studio_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studio_agents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_studio_agents_id'))

    op.drop_table('studio_agents')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_leads_telefone'))
        batch_op.drop_index(batch_op.f('ix_leads_recovery_bloqueado'))
        batch_op.drop_index(batch_op.f('ix_leads_node_atual'))
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_convertido'))
        batch_op.drop_index(batch_op.f('ix_leads_bot_pausado'))

    op.drop_table('leads')
    with op.batch_alter_table('flow_blueprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_blueprints_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprints_slug'))
        batch_op.drop_index(batch_op.f('ix_flow_blueprints_id'))

    op.drop_table('flow_blueprints')
    with op.batch_alter_table('audio_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_cache_id'))
        batch_op.drop_index(batch_op.f('ix_audio_cache_cache_key'))

    op.drop_table('audio_cache')
    # ### end Alembic commands ###
