"""frente2_16 tenant_billing + cancellation_surveys

Revision ID: 6d467c5ec07d
Revises: 40ccdca66cfd
Create Date: 2026-04-29 13:49:16.498721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d467c5ec07d'
down_revision: Union[str, Sequence[str], None] = '40ccdca66cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_billing',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('billing_period', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.String(length=120), nullable=True),
    sa.Column('subscription_id', sa.String(length=120), nullable=True),
    sa.Column('price_id', sa.String(length=120), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_plan', sa.String(length=32), nullable=True),
    sa.Column('pending_billing_period', sa.String(length=10), nullable=True),
    sa.Column('pending_effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mrr_brl_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    with op.batch_alter_table('tenant_billing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_billing_customer_id'), ['customer_id'], unique=False)

    op.create_table('cancellation_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason_category', sa.String(length=40), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('win_back_offered', sa.String(length=40), nullable=True),
    sa.Column('win_back_accepted', sa.Boolean(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cancellation_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cancellation_surveys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cancellation_surveys_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancellation_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cancellation_surveys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cancellation_surveys_id'))

    op.drop_table('cancellation_surveys')
    with op.batch_alter_table('tenant_billing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_billing_customer_id'))

    op.drop_table('tenant_billing')
    # ### end Alembic commands ###
