"""mensagem_delivery_status

Revision ID: 6da93124b93b
Revises: cc44c90edc2e
Create Date: 2026-04-29 20:55:17.777118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da93124b93b'
down_revision: Union[str, Sequence[str], None] = 'cc44c90edc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wamid', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_status_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_mensagens_wamid'), ['wamid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagens_wamid'))
        batch_op.drop_column('delivery_status_at')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('wamid')

    # ### end Alembic commands ###
