"""frente1+2 admin foundation

Revision ID: 6ecad1605ca5
Revises: 5ee5408501f7
Create Date: 2026-04-29 12:45:22.719739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecad1605ca5'
down_revision: Union[str, Sequence[str], None] = '5ee5408501f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_health',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=10), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_usage_counters',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cost_brl_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'period_yyyymm', 'kind')
    )
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('target_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('actions_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impersonation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impersonation_sessions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impersonation_sessions_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_impersonation_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impersonation_sessions_target_tenant_id'), ['target_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impersonation_sessions_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('plan_global_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('field_path', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.Column('set_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_global_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_global_overrides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_global_overrides_plan_key'), ['plan_key'], unique=False)

    op.create_table('tenant_admin_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('author_admin_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_admin_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_admin_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_admin_notes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_plan_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('granted_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pauses_stripe', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_plan_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_plan_overrides_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_plan_overrides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_plan_overrides_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_quota_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('used_amount', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_quota_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_quota_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_quota_grants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_quota_grants_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('totp_recovery_codes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_password_change_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('suspended_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suspension_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_subrole', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=40), nullable=False, server_default='America/Sao_Paulo'))
        batch_op.add_column(sa.Column('theme_preset', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('dashboard_layout', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tours_completed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_changelog_seen_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('trial_extended_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('dunning_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dunning_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_suspended_at'), ['suspended_at'], unique=False)
        batch_op.create_foreign_key('fk_users_suspended_by', 'users', ['suspended_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_suspended_at'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_column('dunning_attempts')
        batch_op.drop_column('dunning_status')
        batch_op.drop_column('trial_extended_count')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('trial_started_at')
        batch_op.drop_column('last_changelog_seen_at')
        batch_op.drop_column('tours_completed')
        batch_op.drop_column('dashboard_layout')
        batch_op.drop_column('theme_preset')
        batch_op.drop_column('timezone')
        batch_op.drop_column('admin_subrole')
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('suspended_by')
        batch_op.drop_column('suspended_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('last_password_change_at')
        batch_op.drop_column('phone_verified_at')
        batch_op.drop_column('phone')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('totp_recovery_codes')
        batch_op.drop_column('totp_enabled_at')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('tenant_quota_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_quota_grants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_quota_grants_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_quota_grants_expires_at'))

    op.drop_table('tenant_quota_grants')
    with op.batch_alter_table('tenant_plan_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_plan_overrides_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_plan_overrides_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_plan_overrides_expires_at'))

    op.drop_table('tenant_plan_overrides')
    with op.batch_alter_table('tenant_admin_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_admin_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_admin_notes_id'))

    op.drop_table('tenant_admin_notes')
    with op.batch_alter_table('plan_global_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_global_overrides_plan_key'))
        batch_op.drop_index(batch_op.f('ix_plan_global_overrides_id'))

    op.drop_table('plan_global_overrides')
    with op.batch_alter_table('impersonation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impersonation_sessions_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_impersonation_sessions_target_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_impersonation_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_impersonation_sessions_ended_at'))
        batch_op.drop_index(batch_op.f('ix_impersonation_sessions_admin_user_id'))

    op.drop_table('impersonation_sessions')
    op.drop_table('tenant_usage_counters')
    op.drop_table('tenant_health')
    # ### end Alembic commands ###
