"""frente4_22_spiritual_dates

Revision ID: 73a2a208e666
Revises: 5b07d79c7608
Create Date: 2026-04-29 15:50:05.902878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a2a208e666'
down_revision: Union[str, Sequence[str], None] = '5b07d79c7608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiritual_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tradition', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recurring', sa.String(length=20), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('fixed_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spiritual_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spiritual_dates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spiritual_dates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spiritual_dates_tradition'), ['tradition'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spiritual_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spiritual_dates_tradition'))
        batch_op.drop_index(batch_op.f('ix_spiritual_dates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_spiritual_dates_id'))

    op.drop_table('spiritual_dates')
    # ### end Alembic commands ###
