"""frente4_18_aura_images

Revision ID: 7b01337bac62
Revises: ac0212d6f574
Create Date: 2026-04-29 15:26:01.504985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b01337bac62'
down_revision: Union[str, Sequence[str], None] = 'ac0212d6f574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_aura_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('signo', sa.String(length=20), nullable=False),
    sa.Column('week_id', sa.String(length=10), nullable=False),
    sa.Column('image_url', sa.String(length=800), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('sent_to_lead', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'week_id', name='uq_aura_lead_week')
    )
    with op.batch_alter_table('lead_aura_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_aura_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_aura_images_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_aura_images_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_aura_images_week_id'), ['week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_aura_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_aura_images_week_id'))
        batch_op.drop_index(batch_op.f('ix_lead_aura_images_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lead_aura_images_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_aura_images_id'))

    op.drop_table('lead_aura_images')
    # ### end Alembic commands ###
