"""frente3_26 flow_node_visits

Revision ID: 894412876bdb
Revises: b25b8eb1c68f
Create Date: 2026-04-29 14:09:24.709103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894412876bdb'
down_revision: Union[str, Sequence[str], None] = 'b25b8eb1c68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_node_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('flow_slug', sa.String(length=120), nullable=True),
    sa.Column('node_id', sa.String(length=120), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flow_node_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_node_visits_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_node_visits_flow_slug'), ['flow_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_node_visits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_node_visits_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_node_visits_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_node_visits_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('score_value',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('score_band',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('score_band',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'cold'"),
               existing_nullable=False)
        batch_op.alter_column('score_value',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('flow_node_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_node_visits_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_flow_node_visits_node_id'))
        batch_op.drop_index(batch_op.f('ix_flow_node_visits_lead_id'))
        batch_op.drop_index(batch_op.f('ix_flow_node_visits_id'))
        batch_op.drop_index(batch_op.f('ix_flow_node_visits_flow_slug'))
        batch_op.drop_index(batch_op.f('ix_flow_node_visits_flow_id'))

    op.drop_table('flow_node_visits')
    # ### end Alembic commands ###
