"""wa_inbound_log

Revision ID: 9dd5153f0b61
Revises: 4c59c59a9a00
Create Date: 2026-04-29 20:12:03.000042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd5153f0b61'
down_revision: Union[str, Sequence[str], None] = '4c59c59a9a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_inbound_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wa_inbound_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wa_inbound_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wa_inbound_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wa_inbound_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wa_inbound_logs_phone_number_id'), ['phone_number_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wa_inbound_logs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_inbound_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wa_inbound_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_wa_inbound_logs_phone_number_id'))
        batch_op.drop_index(batch_op.f('ix_wa_inbound_logs_id'))
        batch_op.drop_index(batch_op.f('ix_wa_inbound_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_wa_inbound_logs_created_at'))

    op.drop_table('wa_inbound_logs')
    # ### end Alembic commands ###
