"""frente4_3_12_natal_numerology

Revision ID: ac0212d6f574
Revises: 16ef806c29dd
Create Date: 2026-04-29 15:20:26.590663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ac0212d6f574'
down_revision: Union[str, Sequence[str], None] = '16ef806c29dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_natal_charts',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_time', sa.String(length=8), nullable=True),
    sa.Column('birth_place', sa.String(length=200), nullable=True),
    sa.Column('birth_lat', sa.Float(), nullable=True),
    sa.Column('birth_lon', sa.Float(), nullable=True),
    sa.Column('timezone_offset', sa.Float(), nullable=False),
    sa.Column('chart_json', sa.JSON(), nullable=True),
    sa.Column('interpretation_text', sa.Text(), nullable=True),
    sa.Column('interpretation_focus', sa.String(length=40), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interpreted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    with op.batch_alter_table('lead_natal_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_natal_charts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lead_numerology',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('life_path', sa.Integer(), nullable=True),
    sa.Column('expression', sa.Integer(), nullable=True),
    sa.Column('soul', sa.Integer(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('interpretation_text', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interpreted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    with op.batch_alter_table('lead_numerology', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_numerology_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('consents',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('consents',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)

    with op.batch_alter_table('lead_numerology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_numerology_tenant_id'))

    op.drop_table('lead_numerology')
    with op.batch_alter_table('lead_natal_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_natal_charts_tenant_id'))

    op.drop_table('lead_natal_charts')
    # ### end Alembic commands ###
