"""frente3_24 lead score columns

Revision ID: b25b8eb1c68f
Revises: 6d467c5ec07d
Create Date: 2026-04-29 14:05:06.052472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25b8eb1c68f'
down_revision: Union[str, Sequence[str], None] = '6d467c5ec07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_value', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('score_band', sa.String(length=10), nullable=False, server_default='cold'))
        batch_op.add_column(sa.Column('score_components', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('score_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_score_band'), ['score_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_score_value'), ['score_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_score_value'))
        batch_op.drop_index(batch_op.f('ix_leads_score_band'))
        batch_op.drop_column('score_updated_at')
        batch_op.drop_column('score_components')
        batch_op.drop_column('score_band')
        batch_op.drop_column('score_value')

    # ### end Alembic commands ###
