"""frente4_2_lunar_triggers

Revision ID: b307ed056fa4
Revises: 3ad6d75bb41a
Create Date: 2026-04-29 14:58:44.605969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b307ed056fa4'
down_revision: Union[str, Sequence[str], None] = '3ad6d75bb41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunar_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('flow_slug', sa.String(length=120), nullable=True),
    sa.Column('trigger_phase', sa.String(length=20), nullable=False),
    sa.Column('window_hours_before', sa.Integer(), nullable=False),
    sa.Column('segment_filter', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lunar_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lunar_triggers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lunar_triggers_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunar_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lunar_triggers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lunar_triggers_id'))

    op.drop_table('lunar_triggers')
    # ### end Alembic commands ###
