"""frente7_14_marketplace

Revision ID: b486d6eb58a5
Revises: b307ed056fa4
Create Date: 2026-04-29 15:03:04.261457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b486d6eb58a5'
down_revision: Union[str, Sequence[str], None] = 'b307ed056fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('flow_template_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('price_brl_cents', sa.Integer(), nullable=False),
    sa.Column('blueprint_json', sa.JSON(), nullable=False),
    sa.Column('agent_json', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('preview_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_admin', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('total_revenue_brl_cents', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_admin'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flow_template_id'], ['flow_templates.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_listings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_seller_tenant_id'), ['seller_tenant_id'], unique=False)

    op.create_table('marketplace_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('amount_brl_cents', sa.Integer(), nullable=False),
    sa.Column('acassia_fee_cents', sa.Integer(), nullable=False),
    sa.Column('seller_payout_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=120), nullable=True),
    sa.Column('pix_payment_id', sa.String(length=120), nullable=True),
    sa.Column('payment_provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_blueprint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_purchases_buyer_tenant_id'), ['buyer_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_purchases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_purchases_listing_id'), ['listing_id'], unique=False)

    op.create_table('marketplace_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['marketplace_purchases.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    with op.batch_alter_table('marketplace_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_reviews_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_reviews_listing_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_reviews_id'))

    op.drop_table('marketplace_reviews')
    with op.batch_alter_table('marketplace_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_purchases_listing_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_purchases_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_purchases_buyer_tenant_id'))

    op.drop_table('marketplace_purchases')
    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_seller_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_id'))

    op.drop_table('marketplace_listings')
    # ### end Alembic commands ###
