"""spiritual_glossary_4_21

Revision ID: c2d2852c9085
Revises: 6da93124b93b
Create Date: 2026-04-29 21:05:25.510265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d2852c9085'
down_revision: Union[str, Sequence[str], None] = '6da93124b93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiritual_glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('usage_examples', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spiritual_glossary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spiritual_glossary_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spiritual_glossary_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spiritual_glossary_term'), ['term'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spiritual_glossary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spiritual_glossary_term'))
        batch_op.drop_index(batch_op.f('ix_spiritual_glossary_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_spiritual_glossary_id'))

    op.drop_table('spiritual_glossary')
    # ### end Alembic commands ###
