"""scheduled_readings_4_28

Revision ID: cc44c90edc2e
Revises: 56a3674793bd
Create Date: 2026-04-29 20:51:58.713137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc44c90edc2e'
down_revision: Union[str, Sequence[str], None] = '56a3674793bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('spread_type', sa.String(length=40), nullable=False),
    sa.Column('deck_id', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warning_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['tarot_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_readings_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_readings_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_readings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_readings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_readings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_readings_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_readings_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_scheduled_readings_lead_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_readings_id'))

    op.drop_table('scheduled_readings')
    # ### end Alembic commands ###
