"""frente1+2 admin actions + audit + flags + quota warnings

Revision ID: ee007d99af8b
Revises: 6ecad1605ca5
Create Date: 2026-04-29 13:10:01.558940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee007d99af8b'
down_revision: Union[str, Sequence[str], None] = '6ecad1605ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Boolean(), nullable=False),
    sa.Column('rollout_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tenant_quota_warnings',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('period_yyyymm', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('threshold_pct', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'period_yyyymm', 'kind', 'threshold_pct')
    )
    op.create_table('tenant_feature_flags',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('flag_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('set_by', sa.Integer(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flag_key'], ['feature_flags.key'], ),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'flag_key')
    )
    op.create_table('eventos_audit_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('impersonator_user_id', sa.Integer(), nullable=True),
    sa.Column('impersonation_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['impersonation_id'], ['impersonation_sessions.id'], ),
    sa.ForeignKeyConstraint(['impersonator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_audit_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_audit_v2_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_audit_v2_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_audit_v2_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_audit_v2_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_audit_v2_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('trial_extended_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('dunning_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('dunning_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('trial_extended_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'America/Sao_Paulo'"),
               existing_nullable=False)
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('eventos_audit_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_audit_v2_timestamp'))
        batch_op.drop_index(batch_op.f('ix_eventos_audit_v2_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_audit_v2_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_audit_v2_event_type'))
        batch_op.drop_index(batch_op.f('ix_eventos_audit_v2_actor_user_id'))

    op.drop_table('eventos_audit_v2')
    op.drop_table('tenant_feature_flags')
    op.drop_table('tenant_quota_warnings')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
