"""tarot_reading_sent_at

Revision ID: f8b260830503
Revises: 7b01337bac62
Create Date: 2026-04-29 15:33:32.871448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b260830503'
down_revision: Union[str, Sequence[str], None] = '7b01337bac62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarot_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarot_readings', schema=None) as batch_op:
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
