"""wa_binding_webhook_path

Revision ID: fdf25ed08916
Revises: 9dd5153f0b61
Create Date: 2026-04-29 20:23:45.928654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf25ed08916'
down_revision: Union[str, Sequence[str], None] = '9dd5153f0b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_phone_tenant_bindings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_path', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_wa_phone_tenant_bindings_webhook_path'), ['webhook_path'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wa_phone_tenant_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wa_phone_tenant_bindings_webhook_path'))
        batch_op.drop_column('webhook_path')

    # ### end Alembic commands ###
